### ISSUE TITLE
ooops! There's a err, please paste this errorstack to the repo's issue list: https://github.com/weexteam/weex-vue-precompiler/issues 

### ISSUE THREAD

**Issue by Xiaoshumiao2021** [weexteam/vue-precompiler-for-apache-weex#10]
{Error: Line 1: Unexpected token ...
    at ErrorHandler.constructError (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parseObjectPropertyKey (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:2499:33)
    at Parser.parseObjectProperty (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:2534:25)
    at Parser.parseObjectInitializer (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:2602:35)
    at Parser.inheritCoverGrammar (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parsePrimaryExpression (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:2354:38)
    at Parser.inheritCoverGrammar (/Users/kingcodexl/.lighting-plugins/lib/node_modules/lighting-plugin-type-vue/node_modules/weex-vue-precompiler/node_modules/esprima/dist/esprima.js:2285:37) index: 46, lineNumber: 1, description: 'Unexpected token ...' }

**Comment by c0decafe** [comment]
see https://github.com/jquery/esprima/issues/1588
